apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zv41u9awa-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/zv41u9awa-java-quarkus-gitops